// This file is generated by kconfig_compiler from amarok.kcfg.
// All changes you do to this file will be lost.
#ifndef AMAROKCONFIG_H
#define AMAROKCONFIG_H

#include <kconfigskeleton.h>
#include <kdebug.h>

#include <qdir.h>
class AmarokConfig : public KConfigSkeleton
{
  public:
    class EnumOsdAlignment
    {
      public:
      enum type { Left, Middle, Center, Right, COUNT };
    };

    static AmarokConfig *self();
    ~AmarokConfig();

    /**
      Set Amarok Version
    */
    static
    void setVersion( const QString & v )
    {
      if (!self()->isImmutable( QString::fromLatin1( "Version" ) ))
        self()->mVersion = v;
    }

    /**
      Get Amarok Version
    */
    static
    QString version()
    {
      return self()->mVersion;
    }

    /**
      Set Position of player window
    */
    static
    void setPlayerPos( const QPoint & v )
    {
      if (!self()->isImmutable( QString::fromLatin1( "PlayerPos" ) ))
        self()->mPlayerPos = v;
    }

    /**
      Get Position of player window
    */
    static
    QPoint playerPos()
    {
      return self()->mPlayerPos;
    }

    /**
      Set Position of playlist window
    */
    static
    void setPlaylistWindowPos( const QPoint & v )
    {
      if (!self()->isImmutable( QString::fromLatin1( "PlaylistWindowPos" ) ))
        self()->mPlaylistWindowPos = v;
    }

    /**
      Get Position of playlist window
    */
    static
    QPoint playlistWindowPos()
    {
      return self()->mPlaylistWindowPos;
    }

    /**
      Set Size of playlist window
    */
    static
    void setPlaylistWindowSize( const QSize & v )
    {
      if (!self()->isImmutable( QString::fromLatin1( "PlaylistWindowSize" ) ))
        self()->mPlaylistWindowSize = v;
    }

    /**
      Get Size of playlist window
    */
    static
    QSize playlistWindowSize()
    {
      return self()->mPlaylistWindowSize;
    }

    /**
      Set Whether to save playlist on quit
    */
    static
    void setSavePlaylist( bool v )
    {
      if (!self()->isImmutable( QString::fromLatin1( "SavePlaylist" ) ))
        self()->mSavePlaylist = v;
    }

    /**
      Get Whether to save playlist on quit
    */
    static
    bool savePlaylist()
    {
      return self()->mSavePlaylist;
    }

    /**
      Set Whether to follow symlinks while adding items to playlist recursively
    */
    static
    void setFollowSymlinks( bool v )
    {
      if (!self()->isImmutable( QString::fromLatin1( "FollowSymlinks" ) ))
        self()->mFollowSymlinks = v;
    }

    /**
      Get Whether to follow symlinks while adding items to playlist recursively
    */
    static
    bool followSymlinks()
    {
      return self()->mFollowSymlinks;
    }

    /**
      Set Whether to display remaining track time
    */
    static
    void setTimeDisplayRemaining( bool v )
    {
      if (!self()->isImmutable( QString::fromLatin1( "TimeDisplayRemaining" ) ))
        self()->mTimeDisplayRemaining = v;
    }

    /**
      Get Whether to display remaining track time
    */
    static
    bool timeDisplayRemaining()
    {
      return self()->mTimeDisplayRemaining;
    }

    /**
      Set Whether to play track repeatedly
    */
    static
    void setRepeatTrack( bool v )
    {
      if (!self()->isImmutable( QString::fromLatin1( "RepeatTrack" ) ))
        self()->mRepeatTrack = v;
    }

    /**
      Get Whether to play track repeatedly
    */
    static
    bool repeatTrack()
    {
      return self()->mRepeatTrack;
    }

    /**
      Set Whether to play whole playlist repeatedly
    */
    static
    void setRepeatPlaylist( bool v )
    {
      if (!self()->isImmutable( QString::fromLatin1( "RepeatPlaylist" ) ))
        self()->mRepeatPlaylist = v;
    }

    /**
      Get Whether to play whole playlist repeatedly
    */
    static
    bool repeatPlaylist()
    {
      return self()->mRepeatPlaylist;
    }

    /**
      Set Whether to play tracks in random order
    */
    static
    void setRandomMode( bool v )
    {
      if (!self()->isImmutable( QString::fromLatin1( "RandomMode" ) ))
        self()->mRandomMode = v;
    }

    /**
      Get Whether to play tracks in random order
    */
    static
    bool randomMode()
    {
      return self()->mRandomMode;
    }

    /**
      Set Plays a dynamic playlist
    */
    static
    void setDynamicMode( bool v )
    {
      if (!self()->isImmutable( QString::fromLatin1( "DynamicMode" ) ))
        self()->mDynamicMode = v;
    }

    /**
      Get Plays a dynamic playlist
    */
    static
    bool dynamicMode()
    {
      return self()->mDynamicMode;
    }

    /**
      Set Shows help
    */
    static
    void setDynamicInfo( bool v )
    {
      if (!self()->isImmutable( QString::fromLatin1( "DynamicInfo" ) ))
        self()->mDynamicInfo = v;
    }

    /**
      Get Shows help
    */
    static
    bool dynamicInfo()
    {
      return self()->mDynamicInfo;
    }

    /**
      Set Adds this type of song
    */
    static
    void setDynamicType( const QString & v )
    {
      if (!self()->isImmutable( QString::fromLatin1( "DynamicType" ) ))
        self()->mDynamicType = v;
    }

    /**
      Get Adds this type of song
    */
    static
    QString dynamicType()
    {
      return self()->mDynamicType;
    }

    /**
      Set List of smart playlists to be appended for dynamic mode.
    */
    static
    void setDynamicCustomList( const QStringList & v )
    {
      if (!self()->isImmutable( QString::fromLatin1( "DynamicCustomList" ) ))
        self()->mDynamicCustomList = v;
    }

    /**
      Get List of smart playlists to be appended for dynamic mode.
    */
    static
    QStringList dynamicCustomList()
    {
      return self()->mDynamicCustomList;
    }

    /**
      Set Number of upcoming songs to show
    */
    static
    void setDynamicUpcomingCount( int v )
    {
      if (!self()->isImmutable( QString::fromLatin1( "DynamicUpcomingCount" ) ))
        self()->mDynamicUpcomingCount = v;
    }

    /**
      Get Number of upcoming songs to show
    */
    static
    int dynamicUpcomingCount()
    {
      return self()->mDynamicUpcomingCount;
    }

    /**
      Set History of songs count
    */
    static
    void setDynamicPreviousCount( int v )
    {
      if (!self()->isImmutable( QString::fromLatin1( "DynamicPreviousCount" ) ))
        self()->mDynamicPreviousCount = v;
    }

    /**
      Get History of songs count
    */
    static
    int dynamicPreviousCount()
    {
      return self()->mDynamicPreviousCount;
    }

    /**
      Set Number of tracks to append
    */
    static
    void setDynamicAppendCount( int v )
    {
      if (!self()->isImmutable( QString::fromLatin1( "DynamicAppendCount" ) ))
        self()->mDynamicAppendCount = v;
    }

    /**
      Get Number of tracks to append
    */
    static
    int dynamicAppendCount()
    {
      return self()->mDynamicAppendCount;
    }

    /**
      Set Cycle Tracks
    */
    static
    void setDynamicCycleTracks( bool v )
    {
      if (!self()->isImmutable( QString::fromLatin1( "DynamicCycleTracks" ) ))
        self()->mDynamicCycleTracks = v;
    }

    /**
      Get Cycle Tracks
    */
    static
    bool dynamicCycleTracks()
    {
      return self()->mDynamicCycleTracks;
    }

    /**
      Set Mark History
    */
    static
    void setDynamicMarkHistory( bool v )
    {
      if (!self()->isImmutable( QString::fromLatin1( "DynamicMarkHistory" ) ))
        self()->mDynamicMarkHistory = v;
    }

    /**
      Get Mark History
    */
    static
    bool dynamicMarkHistory()
    {
      return self()->mDynamicMarkHistory;
    }

    /**
      Set Whether to show icon in system tray
    */
    static
    void setShowTrayIcon( bool v )
    {
      if (!self()->isImmutable( QString::fromLatin1( "ShowTrayIcon" ) ))
        self()->mShowTrayIcon = v;
    }

    /**
      Get Whether to show icon in system tray
    */
    static
    bool showTrayIcon()
    {
      return self()->mShowTrayIcon;
    }

    /**
      Set Whether to animate the systray icon
    */
    static
    void setAnimateTrayIcon( bool v )
    {
      if (!self()->isImmutable( QString::fromLatin1( "AnimateTrayIcon" ) ))
        self()->mAnimateTrayIcon = v;
    }

    /**
      Get Whether to animate the systray icon
    */
    static
    bool animateTrayIcon()
    {
      return self()->mAnimateTrayIcon;
    }

    /**
      Set Whether to show player window
    */
    static
    void setShowPlayerWindow( bool v )
    {
      if (!self()->isImmutable( QString::fromLatin1( "ShowPlayerWindow" ) ))
        self()->mShowPlayerWindow = v;
    }

    /**
      Get Whether to show player window
    */
    static
    bool showPlayerWindow()
    {
      return self()->mShowPlayerWindow;
    }

    /**
      Set Whether to show the toolbar in the playlist window.
    */
    static
    void setShowToolbar( bool v )
    {
      if (!self()->isImmutable( QString::fromLatin1( "ShowToolbar" ) ))
        self()->mShowToolbar = v;
    }

    /**
      Get Whether to show the toolbar in the playlist window.
    */
    static
    bool showToolbar()
    {
      return self()->mShowToolbar;
    }

    /**
      Set Size of the cover previews in Contextbrowser and Covermanager
    */
    static
    void setCoverPreviewSize( int v )
    {
      if (!self()->isImmutable( QString::fromLatin1( "CoverPreviewSize" ) ))
        self()->mCoverPreviewSize = v;
    }

    /**
      Get Size of the cover previews in Contextbrowser and Covermanager
    */
    static
    int coverPreviewSize()
    {
      return self()->mCoverPreviewSize;
    }

    /**
      Set Whether to show the Playlist Statusbar
    */
    static
    void setShowStatusBar( bool v )
    {
      if (!self()->isImmutable( QString::fromLatin1( "ShowStatusBar" ) ))
        self()->mShowStatusBar = v;
    }

    /**
      Get Whether to show the Playlist Statusbar
    */
    static
    bool showStatusBar()
    {
      return self()->mShowStatusBar;
    }

    /**
      Set Whether to add directories to playlist recursively
    */
    static
    void setDirectoriesRecursively( bool v )
    {
      if (!self()->isImmutable( QString::fromLatin1( "DirectoriesRecursively" ) ))
        self()->mDirectoriesRecursively = v;
    }

    /**
      Get Whether to add directories to playlist recursively
    */
    static
    bool directoriesRecursively()
    {
      return self()->mDirectoriesRecursively;
    }

    /**
      Set Delay between tracks, in milliseconds
    */
    static
    void setTrackDelayLength( int v )
    {
      if (!self()->isImmutable( QString::fromLatin1( "TrackDelayLength" ) ))
        self()->mTrackDelayLength = v;
    }

    /**
      Get Delay between tracks, in milliseconds
    */
    static
    int trackDelayLength()
    {
      return self()->mTrackDelayLength;
    }

    /**
      Set Whether the playlist window is visible
    */
    static
    void setPlaylistWindowEnabled( bool v )
    {
      if (!self()->isImmutable( QString::fromLatin1( "PlaylistWindowEnabled" ) ))
        self()->mPlaylistWindowEnabled = v;
    }

    /**
      Get Whether the playlist window is visible
    */
    static
    bool playlistWindowEnabled()
    {
      return self()->mPlaylistWindowEnabled;
    }

    /**
      Set Number of undo levels in playlist
    */
    static
    void setUndoLevels( int v )
    {
      if (!self()->isImmutable( QString::fromLatin1( "UndoLevels" ) ))
        self()->mUndoLevels = v;
    }

    /**
      Get Number of undo levels in playlist
    */
    static
    int undoLevels()
    {
      return self()->mUndoLevels;
    }

    /**
      Set Index of current visual analyzer
    */
    static
    void setCurrentAnalyzer( int v )
    {
      if (!self()->isImmutable( QString::fromLatin1( "CurrentAnalyzer" ) ))
        self()->mCurrentAnalyzer = v;
    }

    /**
      Get Index of current visual analyzer
    */
    static
    int currentAnalyzer()
    {
      return self()->mCurrentAnalyzer;
    }

    /**
      Set Index of analyzer displayed in playlist window
    */
    static
    void setCurrentPlaylistAnalyzer( int v )
    {
      if (!self()->isImmutable( QString::fromLatin1( "CurrentPlaylistAnalyzer" ) ))
        self()->mCurrentPlaylistAnalyzer = v;
    }

    /**
      Get Index of analyzer displayed in playlist window
    */
    static
    int currentPlaylistAnalyzer()
    {
      return self()->mCurrentPlaylistAnalyzer;
    }

    /**
      Set Playlist window splitter positions
    */
    static
    void setPlaylistWindowSplitter( const QValueList<int> & v )
    {
      if (!self()->isImmutable( QString::fromLatin1( "PlaylistWindowSplitter" ) ))
        self()->mPlaylistWindowSplitter = v;
    }

    /**
      Get Playlist window splitter positions
    */
    static
    QValueList<int> playlistWindowSplitter()
    {
      return self()->mPlaylistWindowSplitter;
    }

    /**
      Set Whether the playlist should scroll with the active playlist item
    */
    static
    void setPlaylistFollowActive( bool v )
    {
      if (!self()->isImmutable( QString::fromLatin1( "PlaylistFollowActive" ) ))
        self()->mPlaylistFollowActive = v;
    }

    /**
      Get Whether the playlist should scroll with the active playlist item
    */
    static
    bool playlistFollowActive()
    {
      return self()->mPlaylistFollowActive;
    }

    /**
      Set Whether a splash-screen should be displayed on startup
    */
    static
    void setShowSplashscreen( bool v )
    {
      if (!self()->isImmutable( QString::fromLatin1( "ShowSplashscreen" ) ))
        self()->mShowSplashscreen = v;
    }

    /**
      Get Whether a splash-screen should be displayed on startup
    */
    static
    bool showSplashscreen()
    {
      return self()->mShowSplashscreen;
    }

    /**
      Set Whether ContextBrowser should be activated when starting playback
    */
    static
    void setAutoShowContextBrowser( bool v )
    {
      if (!self()->isImmutable( QString::fromLatin1( "AutoShowContextBrowser" ) ))
        self()->mAutoShowContextBrowser = v;
    }

    /**
      Get Whether ContextBrowser should be activated when starting playback
    */
    static
    bool autoShowContextBrowser()
    {
      return self()->mAutoShowContextBrowser;
    }

    /**
      Set Whether ContextBrowser should show statistics by albums when it is possible.
    */
    static
    void setShowStatByAlbums( bool v )
    {
      if (!self()->isImmutable( QString::fromLatin1( "ShowStatByAlbums" ) ))
        self()->mShowStatByAlbums = v;
    }

    /**
      Get Whether ContextBrowser should show statistics by albums when it is possible.
    */
    static
    bool showStatByAlbums()
    {
      return self()->mShowStatByAlbums;
    }

    /**
      Set Set CSS stylesheet used to customize ContextBrowser's rendering
    */
    static
    void setContextBrowserStyleSheet( const QString & v )
    {
      if (!self()->isImmutable( QString::fromLatin1( "ContextBrowserStyleSheet" ) ))
        self()->mContextBrowserStyleSheet = v;
    }

    /**
      Get Set CSS stylesheet used to customize ContextBrowser's rendering
    */
    static
    QString contextBrowserStyleSheet()
    {
      return self()->mContextBrowserStyleSheet;
    }

    /**
      Set Whether Menubar is shown
    */
    static
    void setShowMenuBar( bool v )
    {
      if (!self()->isImmutable( QString::fromLatin1( "ShowMenuBar" ) ))
        self()->mShowMenuBar = v;
    }

    /**
      Get Whether Menubar is shown
    */
    static
    bool showMenuBar()
    {
      return self()->mShowMenuBar;
    }

    /**
      Set Whether playlists store relative path
    */
    static
    void setRelativePlaylist( bool v )
    {
      if (!self()->isImmutable( QString::fromLatin1( "RelativePlaylist" ) ))
        self()->mRelativePlaylist = v;
    }

    /**
      Get Whether playlists store relative path
    */
    static
    bool relativePlaylist()
    {
      return self()->mRelativePlaylist;
    }

    /**
      Set Master volume
    */
    static
    void setMasterVolume( int v )
    {
      if (v < 0)
      {
        kdDebug() << "setMasterVolume: value " << v << " is less than the minimum value of 0" << endl;
        v = 0;
      }

      if (v > 100)
      {
        kdDebug() << "setMasterVolume: value " << v << " is greater than the maximum value of 100" << endl;
        v = 100;
      }

      if (!self()->isImmutable( QString::fromLatin1( "MasterVolume" ) ))
        self()->mMasterVolume = v;
    }

    /**
      Get Master volume
    */
    static
    int masterVolume()
    {
      return self()->mMasterVolume;
    }

    /**
      Set Whether to crossfade between tracks
    */
    static
    void setCrossfade( bool v )
    {
      if (!self()->isImmutable( QString::fromLatin1( "Crossfade" ) ))
        self()->mCrossfade = v;
    }

    /**
      Get Whether to crossfade between tracks
    */
    static
    bool crossfade()
    {
      return self()->mCrossfade;
    }

    /**
      Set Length of crossfade, in milliseconds
    */
    static
    void setCrossfadeLength( int v )
    {
      if (v < 1500)
      {
        kdDebug() << "setCrossfadeLength: value " << v << " is less than the minimum value of 1500" << endl;
        v = 1500;
      }
      if (!self()->isImmutable( QString::fromLatin1( "CrossfadeLength" ) ))
        self()->mCrossfadeLength = v;
    }

    /**
      Get Length of crossfade, in milliseconds
    */
    static
    int crossfadeLength()
    {
      return self()->mCrossfadeLength;
    }

    /**
      Set Sound system to use
    */
    static
    void setSoundSystem( const QString & v )
    {
      if (!self()->isImmutable( QString::fromLatin1( "SoundSystem" ) ))
        self()->mSoundSystem = v;
    }

    /**
      Get Sound system to use
    */
    static
    QString soundSystem()
    {
      return self()->mSoundSystem;
    }

    /**
      Set Enables the equalizer plugin
    */
    static
    void setEqualizerEnabled( bool v )
    {
      if (!self()->isImmutable( QString::fromLatin1( "EqualizerEnabled" ) ))
        self()->mEqualizerEnabled = v;
    }

    /**
      Get Enables the equalizer plugin
    */
    static
    bool equalizerEnabled()
    {
      return self()->mEqualizerEnabled;
    }

    /**
      Set Equalizer pre-amplification value, range -100..100, 0 is normal.
    */
    static
    void setEqualizerPreamp( int v )
    {
      if (v < -100)
      {
        kdDebug() << "setEqualizerPreamp: value " << v << " is less than the minimum value of -100" << endl;
        v = -100;
      }

      if (v > 100)
      {
        kdDebug() << "setEqualizerPreamp: value " << v << " is greater than the maximum value of 100" << endl;
        v = 100;
      }

      if (!self()->isImmutable( QString::fromLatin1( "EqualizerPreamp" ) ))
        self()->mEqualizerPreamp = v;
    }

    /**
      Get Equalizer pre-amplification value, range -100..100, 0 is normal.
    */
    static
    int equalizerPreamp()
    {
      return self()->mEqualizerPreamp;
    }

    /**
      Set Band gains for equalizer, 10 values, range -100..100, 0 is normal.
    */
    static
    void setEqualizerGains( const QValueList<int> & v )
    {
      if (!self()->isImmutable( QString::fromLatin1( "EqualizerGains" ) ))
        self()->mEqualizerGains = v;
    }

    /**
      Get Band gains for equalizer, 10 values, range -100..100, 0 is normal.
    */
    static
    QValueList<int> equalizerGains()
    {
      return self()->mEqualizerGains;
    }

    /**
      Set Equalizer preset name.
    */
    static
    void setEqualizerPreset( const QString & v )
    {
      if (!self()->isImmutable( QString::fromLatin1( "EqualizerPreset" ) ))
        self()->mEqualizerPreset = v;
    }

    /**
      Get Equalizer preset name.
    */
    static
    QString equalizerPreset()
    {
      return self()->mEqualizerPreset;
    }

    /**
      Set Amazon locale for cover retrieval
    */
    static
    void setAmazonLocale( const QString & v )
    {
      if (!self()->isImmutable( QString::fromLatin1( "AmazonLocale" ) ))
        self()->mAmazonLocale = v;
    }

    /**
      Get Amazon locale for cover retrieval
    */
    static
    QString amazonLocale()
    {
      return self()->mAmazonLocale;
    }

    /**
      Set Wikipedia locale for information retrieval
    */
    static
    void setWikipediaLocale( const QString & v )
    {
      if (!self()->isImmutable( QString::fromLatin1( "WikipediaLocale" ) ))
        self()->mWikipediaLocale = v;
    }

    /**
      Get Wikipedia locale for information retrieval
    */
    static
    QString wikipediaLocale()
    {
      return self()->mWikipediaLocale;
    }

    /**
      Set Use On-Screen Display
    */
    static
    void setOsdEnabled( bool v )
    {
      if (!self()->isImmutable( QString::fromLatin1( "OsdEnabled" ) ))
        self()->mOsdEnabled = v;
    }

    /**
      Get Use On-Screen Display
    */
    static
    bool osdEnabled()
    {
      return self()->mOsdEnabled;
    }

    /**
      Set Display the same information in the OSD as in the playlist columns.
    */
    static
    void setOsdUsePlaylistColumns( bool v )
    {
      if (!self()->isImmutable( QString::fromLatin1( "OsdUsePlaylistColumns" ) ))
        self()->mOsdUsePlaylistColumns = v;
    }

    /**
      Get Display the same information in the OSD as in the playlist columns.
    */
    static
    bool osdUsePlaylistColumns()
    {
      return self()->mOsdUsePlaylistColumns;
    }

    /**
      Set The OSD text to show
    */
    static
    void setOsdText( const QString & v )
    {
      if (!self()->isImmutable( QString::fromLatin1( "OsdText" ) ))
        self()->mOsdText = v;
    }

    /**
      Get The OSD text to show
    */
    static
    QString osdText()
    {
      return self()->mOsdText;
    }

    /**
      Set Font for On-Screen Display
    */
    static
    void setOsdFont( const QFont & v )
    {
      if (!self()->isImmutable( QString::fromLatin1( "OsdFont" ) ))
        self()->mOsdFont = v;
    }

    /**
      Get Font for On-Screen Display
    */
    static
    QFont osdFont()
    {
      return self()->mOsdFont;
    }

    /**
      Set Draw a shadow around the text.
    */
    static
    void setOsdDrawShadow( bool v )
    {
      if (!self()->isImmutable( QString::fromLatin1( "OsdDrawShadow" ) ))
        self()->mOsdDrawShadow = v;
    }

    /**
      Get Draw a shadow around the text.
    */
    static
    bool osdDrawShadow()
    {
      return self()->mOsdDrawShadow;
    }

    /**
      Set Fake-translucency Toggle
    */
    static
    void setOsdUseFakeTranslucency( bool v )
    {
      if (!self()->isImmutable( QString::fromLatin1( "OsdUseFakeTranslucency" ) ))
        self()->mOsdUseFakeTranslucency = v;
    }

    /**
      Get Fake-translucency Toggle
    */
    static
    bool osdUseFakeTranslucency()
    {
      return self()->mOsdUseFakeTranslucency;
    }

    /**
      Set Whether to use custom colors for the OSD
    */
    static
    void setOsdUseCustomColors( bool v )
    {
      if (!self()->isImmutable( QString::fromLatin1( "OsdUseCustomColors" ) ))
        self()->mOsdUseCustomColors = v;
    }

    /**
      Get Whether to use custom colors for the OSD
    */
    static
    bool osdUseCustomColors()
    {
      return self()->mOsdUseCustomColors;
    }

    /**
      Set Font Color for On-Screen Display
    */
    static
    void setOsdTextColor( const QColor & v )
    {
      if (!self()->isImmutable( QString::fromLatin1( "OsdTextColor" ) ))
        self()->mOsdTextColor = v;
    }

    /**
      Get Font Color for On-Screen Display
    */
    static
    QColor osdTextColor()
    {
      return self()->mOsdTextColor;
    }

    /**
      Set Background Color for On-Screen Display
    */
    static
    void setOsdBackgroundColor( const QColor & v )
    {
      if (!self()->isImmutable( QString::fromLatin1( "OsdBackgroundColor" ) ))
        self()->mOsdBackgroundColor = v;
    }

    /**
      Get Background Color for On-Screen Display
    */
    static
    QColor osdBackgroundColor()
    {
      return self()->mOsdBackgroundColor;
    }

    /**
      Set How many milliseconds the text should be displayed
    */
    static
    void setOsdDuration( int v )
    {
      if (v < 0)
      {
        kdDebug() << "setOsdDuration: value " << v << " is less than the minimum value of 0" << endl;
        v = 0;
      }
      if (!self()->isImmutable( QString::fromLatin1( "OsdDuration" ) ))
        self()->mOsdDuration = v;
    }

    /**
      Get How many milliseconds the text should be displayed
    */
    static
    int osdDuration()
    {
      return self()->mOsdDuration;
    }

    /**
      Set Y position offset
    */
    static
    void setOsdYOffset( int v )
    {
      if (v < 0)
      {
        kdDebug() << "setOsdYOffset: value " << v << " is less than the minimum value of 0" << endl;
        v = 0;
      }

      if (v > 10000)
      {
        kdDebug() << "setOsdYOffset: value " << v << " is greater than the maximum value of 10000" << endl;
        v = 10000;
      }

      if (!self()->isImmutable( QString::fromLatin1( "OsdYOffset" ) ))
        self()->mOsdYOffset = v;
    }

    /**
      Get Y position offset
    */
    static
    int osdYOffset()
    {
      return self()->mOsdYOffset;
    }

    /**
      Set OSD screen
    */
    static
    void setOsdScreen( int v )
    {
      if (!self()->isImmutable( QString::fromLatin1( "OsdScreen" ) ))
        self()->mOsdScreen = v;
    }

    /**
      Get OSD screen
    */
    static
    int osdScreen()
    {
      return self()->mOsdScreen;
    }

    /**
      Set Whether the album cover should be shown
    */
    static
    void setOsdCover( bool v )
    {
      if (!self()->isImmutable( QString::fromLatin1( "OsdCover" ) ))
        self()->mOsdCover = v;
    }

    /**
      Get Whether the album cover should be shown
    */
    static
    bool osdCover()
    {
      return self()->mOsdCover;
    }

    /**
      Set Align OSD to
    */
    static
    void setOsdAlignment( int v )
    {
      if (!self()->isImmutable( QString::fromLatin1( "OsdAlignment" ) ))
        self()->mOsdAlignment = v;
    }

    /**
      Get Align OSD to
    */
    static
    int osdAlignment()
    {
      return self()->mOsdAlignment;
    }

    /**
      Set Whether to use user-defined fonts
    */
    static
    void setUseCustomFonts( bool v )
    {
      if (!self()->isImmutable( QString::fromLatin1( "UseCustomFonts" ) ))
        self()->mUseCustomFonts = v;
    }

    /**
      Get Whether to use user-defined fonts
    */
    static
    bool useCustomFonts()
    {
      return self()->mUseCustomFonts;
    }

    /**
      Set Font in playlist window
    */
    static
    void setPlaylistWindowFont( const QFont & v )
    {
      if (!self()->isImmutable( QString::fromLatin1( "PlaylistWindowFont" ) ))
        self()->mPlaylistWindowFont = v;
    }

    /**
      Get Font in playlist window
    */
    static
    QFont playlistWindowFont()
    {
      return self()->mPlaylistWindowFont;
    }

    /**
      Set Font in player window
    */
    static
    void setPlayerWidgetFont( const QFont & v )
    {
      if (!self()->isImmutable( QString::fromLatin1( "PlayerWidgetFont" ) ))
        self()->mPlayerWidgetFont = v;
    }

    /**
      Get Font in player window
    */
    static
    QFont playerWidgetFont()
    {
      return self()->mPlayerWidgetFont;
    }

    /**
      Set Font in context browser
    */
    static
    void setContextBrowserFont( const QFont & v )
    {
      if (!self()->isImmutable( QString::fromLatin1( "ContextBrowserFont" ) ))
        self()->mContextBrowserFont = v;
    }

    /**
      Get Font in context browser
    */
    static
    QFont contextBrowserFont()
    {
      return self()->mContextBrowserFont;
    }

    /**
      Set Recode ID3v1 tags
    */
    static
    void setRecodeID3v1Tags( bool v )
    {
      if (!self()->isImmutable( QString::fromLatin1( "RecodeID3v1Tags" ) ))
        self()->mRecodeID3v1Tags = v;
    }

    /**
      Get Recode ID3v1 tags
    */
    static
    bool recodeID3v1Tags()
    {
      return self()->mRecodeID3v1Tags;
    }

    /**
      Set Recode Shoutcast Metadata
    */
    static
    void setRecodeShoutcastMetadata( bool v )
    {
      if (!self()->isImmutable( QString::fromLatin1( "RecodeShoutcastMetadata" ) ))
        self()->mRecodeShoutcastMetadata = v;
    }

    /**
      Get Recode Shoutcast Metadata
    */
    static
    bool recodeShoutcastMetadata()
    {
      return self()->mRecodeShoutcastMetadata;
    }

    /**
      Set Recode encoding
    */
    static
    void setRecodeEncoding( int v )
    {
      if (!self()->isImmutable( QString::fromLatin1( "RecodeEncoding" ) ))
        self()->mRecodeEncoding = v;
    }

    /**
      Get Recode encoding
    */
    static
    int recodeEncoding()
    {
      return self()->mRecodeEncoding;
    }

    /**
      Set Whether to use amaroK standard colors in the playlist window
    */
    static
    void setSchemeAmarok( bool v )
    {
      if (!self()->isImmutable( QString::fromLatin1( "SchemeAmarok" ) ))
        self()->mSchemeAmarok = v;
    }

    /**
      Get Whether to use amaroK standard colors in the playlist window
    */
    static
    bool schemeAmarok()
    {
      return self()->mSchemeAmarok;
    }

    /**
      Set Whether to use global KDE colors in the playlist window
    */
    static
    void setSchemeKDE( bool v )
    {
      if (!self()->isImmutable( QString::fromLatin1( "SchemeKDE" ) ))
        self()->mSchemeKDE = v;
    }

    /**
      Get Whether to use global KDE colors in the playlist window
    */
    static
    bool schemeKDE()
    {
      return self()->mSchemeKDE;
    }

    /**
      Set Whether to use user-defined colors in the playlist window
    */
    static
    void setSchemeCustom( bool v )
    {
      if (!self()->isImmutable( QString::fromLatin1( "SchemeCustom" ) ))
        self()->mSchemeCustom = v;
    }

    /**
      Get Whether to use user-defined colors in the playlist window
    */
    static
    bool schemeCustom()
    {
      return self()->mSchemeCustom;
    }

    /**
      Set Playlist window foreground color
    */
    static
    void setPlaylistWindowFgColor( const QColor & v )
    {
      if (!self()->isImmutable( QString::fromLatin1( "PlaylistWindowFgColor" ) ))
        self()->mPlaylistWindowFgColor = v;
    }

    /**
      Get Playlist window foreground color
    */
    static
    QColor playlistWindowFgColor()
    {
      return self()->mPlaylistWindowFgColor;
    }

    /**
      Set Playlist window background color
    */
    static
    void setPlaylistWindowBgColor( const QColor & v )
    {
      if (!self()->isImmutable( QString::fromLatin1( "PlaylistWindowBgColor" ) ))
        self()->mPlaylistWindowBgColor = v;
    }

    /**
      Get Playlist window background color
    */
    static
    QColor playlistWindowBgColor()
    {
      return self()->mPlaylistWindowBgColor;
    }

    /**
      Set Resume playback of last played track on startup
    */
    static
    void setResumePlayback( bool v )
    {
      if (!self()->isImmutable( QString::fromLatin1( "ResumePlayback" ) ))
        self()->mResumePlayback = v;
    }

    /**
      Get Resume playback of last played track on startup
    */
    static
    bool resumePlayback()
    {
      return self()->mResumePlayback;
    }

    /**
      Set Track URL to resume upon startup
    */
    static
    void setResumeTrack( const QString & v )
    {
      if (!self()->isImmutable( QString::fromLatin1( "ResumeTrack" ) ))
        self()->mResumeTrack = v;
    }

    /**
      Get Track URL to resume upon startup
    */
    static
    QString resumeTrack()
    {
      return self()->mResumeTrack;
    }

    /**
      Set Time to resume at, in milliseconds
    */
    static
    void setResumeTime( int v )
    {
      if (!self()->isImmutable( QString::fromLatin1( "ResumeTime" ) ))
        self()->mResumeTime = v;
    }

    /**
      Get Time to resume at, in milliseconds
    */
    static
    int resumeTime()
    {
      return self()->mResumeTime;
    }

    /**
      Set Database Engine
    */
    static
    void setDatabaseEngine( const QString & v )
    {
      if (!self()->isImmutable( QString::fromLatin1( "DatabaseEngine" ) ))
        self()->mDatabaseEngine = v;
    }

    /**
      Get Database Engine
    */
    static
    QString databaseEngine()
    {
      return self()->mDatabaseEngine;
    }

    /**
      Set Whether Collections folders are scanned recursively
    */
    static
    void setScanRecursively( bool v )
    {
      if (!self()->isImmutable( QString::fromLatin1( "ScanRecursively" ) ))
        self()->mScanRecursively = v;
    }

    /**
      Get Whether Collections folders are scanned recursively
    */
    static
    bool scanRecursively()
    {
      return self()->mScanRecursively;
    }

    /**
      Set Whether Collection folders are rescanned on change
    */
    static
    void setMonitorChanges( bool v )
    {
      if (!self()->isImmutable( QString::fromLatin1( "MonitorChanges" ) ))
        self()->mMonitorChanges = v;
    }

    /**
      Get Whether Collection folders are rescanned on change
    */
    static
    bool monitorChanges()
    {
      return self()->mMonitorChanges;
    }

    /**
      Set Whether playlists should be added while scanning
    */
    static
    void setImportPlaylists( bool v )
    {
      if (!self()->isImmutable( QString::fromLatin1( "ImportPlaylists" ) ))
        self()->mImportPlaylists = v;
    }

    /**
      Get Whether playlists should be added while scanning
    */
    static
    bool importPlaylists()
    {
      return self()->mImportPlaylists;
    }

    /**
      Set List of folders in the Collection
    */
    static
    void setCollectionFolders( const QStringList & v )
    {
      if (!self()->isImmutable( QString::fromLatin1( "CollectionFolders" ) ))
        self()->mCollectionFolders = v;
    }

    /**
      Get List of folders in the Collection
    */
    static
    QStringList collectionFolders()
    {
      return self()->mCollectionFolders;
    }

    /**
      Set Host
    */
    static
    void setMySqlHost( const QString & v )
    {
      if (!self()->isImmutable( QString::fromLatin1( "MySqlHost" ) ))
        self()->mMySqlHost = v;
    }

    /**
      Get Host
    */
    static
    QString mySqlHost()
    {
      return self()->mMySqlHost;
    }

    /**
      Set Port
    */
    static
    void setMySqlPort( int v )
    {
      if (!self()->isImmutable( QString::fromLatin1( "MySqlPort" ) ))
        self()->mMySqlPort = v;
    }

    /**
      Get Port
    */
    static
    int mySqlPort()
    {
      return self()->mMySqlPort;
    }

    /**
      Set Database name
    */
    static
    void setMySqlDbName( const QString & v )
    {
      if (!self()->isImmutable( QString::fromLatin1( "MySqlDbName" ) ))
        self()->mMySqlDbName = v;
    }

    /**
      Get Database name
    */
    static
    QString mySqlDbName()
    {
      return self()->mMySqlDbName;
    }

    /**
      Set User
    */
    static
    void setMySqlUser( const QString & v )
    {
      if (!self()->isImmutable( QString::fromLatin1( "MySqlUser" ) ))
        self()->mMySqlUser = v;
    }

    /**
      Get User
    */
    static
    QString mySqlUser()
    {
      return self()->mMySqlUser;
    }

    /**
      Set Password
    */
    static
    void setMySqlPassword( const QString & v )
    {
      if (!self()->isImmutable( QString::fromLatin1( "MySqlPassword" ) ))
        self()->mMySqlPassword = v;
    }

    /**
      Get Password
    */
    static
    QString mySqlPassword()
    {
      return self()->mMySqlPassword;
    }

    /**
      Set Conninfo
    */
    static
    void setPostgresqlConninfo( const QString & v )
    {
      if (!self()->isImmutable( QString::fromLatin1( "PostgresqlConninfo" ) ))
        self()->mPostgresqlConninfo = v;
    }

    /**
      Get Conninfo
    */
    static
    QString postgresqlConninfo()
    {
      return self()->mPostgresqlConninfo;
    }

    /**
      Set SubmitPlayedSongs
    */
    static
    void setSubmitPlayedSongs( bool v )
    {
      if (!self()->isImmutable( QString::fromLatin1( "SubmitPlayedSongs" ) ))
        self()->mSubmitPlayedSongs = v;
    }

    /**
      Get SubmitPlayedSongs
    */
    static
    bool submitPlayedSongs()
    {
      return self()->mSubmitPlayedSongs;
    }

    /**
      Set Username
    */
    static
    void setScrobblerUsername( const QString & v )
    {
      if (!self()->isImmutable( QString::fromLatin1( "ScrobblerUsername" ) ))
        self()->mScrobblerUsername = v;
    }

    /**
      Get Username
    */
    static
    QString scrobblerUsername()
    {
      return self()->mScrobblerUsername;
    }

    /**
      Set Password
    */
    static
    void setScrobblerPassword( const QString & v )
    {
      if (!self()->isImmutable( QString::fromLatin1( "ScrobblerPassword" ) ))
        self()->mScrobblerPassword = v;
    }

    /**
      Get Password
    */
    static
    QString scrobblerPassword()
    {
      return self()->mScrobblerPassword;
    }

    /**
      Set RetrieveSimilarArtists
    */
    static
    void setRetrieveSimilarArtists( bool v )
    {
      if (!self()->isImmutable( QString::fromLatin1( "RetrieveSimilarArtists" ) ))
        self()->mRetrieveSimilarArtists = v;
    }

    /**
      Get RetrieveSimilarArtists
    */
    static
    bool retrieveSimilarArtists()
    {
      return self()->mRetrieveSimilarArtists;
    }

    /**
      Set MountCommand
    */
    static
    void setMountCommand( const QString & v )
    {
      if (!self()->isImmutable( QString::fromLatin1( "MountCommand" ) ))
        self()->mMountCommand = v;
    }

    /**
      Get MountCommand
    */
    static
    QString mountCommand()
    {
      return self()->mMountCommand;
    }

    /**
      Set UmountCommand
    */
    static
    void setUmountCommand( const QString & v )
    {
      if (!self()->isImmutable( QString::fromLatin1( "UmountCommand" ) ))
        self()->mUmountCommand = v;
    }

    /**
      Get UmountCommand
    */
    static
    QString umountCommand()
    {
      return self()->mUmountCommand;
    }

    static
    void writeConfig()
    {
      static_cast<KConfigSkeleton*>(self())->writeConfig();
    }
  protected:
    AmarokConfig();
    static AmarokConfig *mSelf;


    // General Options
    QString mVersion;
    QPoint mPlayerPos;
    QPoint mPlaylistWindowPos;
    QSize mPlaylistWindowSize;
    bool mSavePlaylist;
    bool mFollowSymlinks;
    bool mTimeDisplayRemaining;
    bool mRepeatTrack;
    bool mRepeatPlaylist;
    bool mRandomMode;
    bool mDynamicMode;
    bool mDynamicInfo;
    QString mDynamicType;
    QStringList mDynamicCustomList;
    int mDynamicUpcomingCount;
    int mDynamicPreviousCount;
    int mDynamicAppendCount;
    bool mDynamicCycleTracks;
    bool mDynamicMarkHistory;
    bool mShowTrayIcon;
    bool mAnimateTrayIcon;
    bool mShowPlayerWindow;
    bool mShowToolbar;
    int mCoverPreviewSize;
    bool mShowStatusBar;
    bool mDirectoriesRecursively;
    int mTrackDelayLength;
    bool mPlaylistWindowEnabled;
    int mUndoLevels;
    int mCurrentAnalyzer;
    int mCurrentPlaylistAnalyzer;
    QValueList<int> mPlaylistWindowSplitter;
    bool mPlaylistFollowActive;
    bool mShowSplashscreen;
    bool mAutoShowContextBrowser;
    bool mShowStatByAlbums;
    QString mContextBrowserStyleSheet;
    bool mShowMenuBar;
    bool mRelativePlaylist;

    // Playback
    int mMasterVolume;
    bool mCrossfade;
    int mCrossfadeLength;
    QString mSoundSystem;
    bool mEqualizerEnabled;
    int mEqualizerPreamp;
    QValueList<int> mEqualizerGains;
    QString mEqualizerPreset;

    // Cover Manager
    QString mAmazonLocale;

    // Wikipedia
    QString mWikipediaLocale;

    // OSD
    bool mOsdEnabled;
    bool mOsdUsePlaylistColumns;
    QString mOsdText;
    QFont mOsdFont;
    bool mOsdDrawShadow;
    bool mOsdUseFakeTranslucency;
    bool mOsdUseCustomColors;
    QColor mOsdTextColor;
    QColor mOsdBackgroundColor;
    int mOsdDuration;
    int mOsdYOffset;
    int mOsdScreen;
    bool mOsdCover;
    int mOsdAlignment;

    // Fonts
    bool mUseCustomFonts;
    QFont mPlaylistWindowFont;
    QFont mPlayerWidgetFont;
    QFont mContextBrowserFont;
    bool mRecodeID3v1Tags;
    bool mRecodeShoutcastMetadata;
    int mRecodeEncoding;

    // Colors
    bool mSchemeAmarok;
    bool mSchemeKDE;
    bool mSchemeCustom;
    QColor mPlaylistWindowFgColor;
    QColor mPlaylistWindowBgColor;

    // Session
    bool mResumePlayback;
    QString mResumeTrack;
    int mResumeTime;

    // Collection
    QString mDatabaseEngine;
    bool mScanRecursively;
    bool mMonitorChanges;
    bool mImportPlaylists;
    QStringList mCollectionFolders;

    // MySql
    QString mMySqlHost;
    int mMySqlPort;
    QString mMySqlDbName;
    QString mMySqlUser;
    QString mMySqlPassword;

    // Postgresql
    QString mPostgresqlConninfo;

    // Scrobbler
    bool mSubmitPlayedSongs;
    QString mScrobblerUsername;
    QString mScrobblerPassword;
    bool mRetrieveSimilarArtists;

    // MediaDevice
    QString mMountCommand;
    QString mUmountCommand;

  private:
};

#endif

