// This file is generated by kconfig_compiler from amarok.kcfg.
// All changes you do to this file will be lost.

#include "amarokconfig.h"

#include <kstaticdeleter.h>

AmarokConfig *AmarokConfig::mSelf = 0;
static KStaticDeleter<AmarokConfig> staticAmarokConfigDeleter;

AmarokConfig *AmarokConfig::self()
{
  if ( !mSelf ) {
    staticAmarokConfigDeleter.setObject( mSelf, new AmarokConfig() );
    mSelf->readConfig();
  }

  return mSelf;
}

AmarokConfig::AmarokConfig(  )
  : KConfigSkeleton( QString::fromLatin1( "amarokrc" ) )
{
  mSelf = this;
  setCurrentGroup( QString::fromLatin1( "General Options" ) );

  KConfigSkeleton::ItemString  *itemVersion;
  itemVersion = new KConfigSkeleton::ItemString( currentGroup(), QString::fromLatin1( "Version" ), mVersion );
  addItem( itemVersion, QString::fromLatin1( "Version" ) );
  KConfigSkeleton::ItemPoint  *itemPlayerPos;
  itemPlayerPos = new KConfigSkeleton::ItemPoint( currentGroup(), QString::fromLatin1( "Player Pos" ), mPlayerPos );
  addItem( itemPlayerPos, QString::fromLatin1( "PlayerPos" ) );
  KConfigSkeleton::ItemBool  *itemPlayerWindowMinimalView;
  itemPlayerWindowMinimalView = new KConfigSkeleton::ItemBool( currentGroup(), QString::fromLatin1( "Player Window Minimal View" ), mPlayerWindowMinimalView, false );
  addItem( itemPlayerWindowMinimalView, QString::fromLatin1( "PlayerWindowMinimalView" ) );
  KConfigSkeleton::ItemPoint  *itemPlaylistWindowPos;
  itemPlaylistWindowPos = new KConfigSkeleton::ItemPoint( currentGroup(), QString::fromLatin1( "Playlist Window Pos" ), mPlaylistWindowPos );
  addItem( itemPlaylistWindowPos, QString::fromLatin1( "PlaylistWindowPos" ) );
  KConfigSkeleton::ItemSize  *itemPlaylistWindowSize;
  itemPlaylistWindowSize = new KConfigSkeleton::ItemSize( currentGroup(), QString::fromLatin1( "Playlist Window Size" ), mPlaylistWindowSize );
  addItem( itemPlaylistWindowSize, QString::fromLatin1( "PlaylistWindowSize" ) );
  KConfigSkeleton::ItemBool  *itemSavePlaylist;
  itemSavePlaylist = new KConfigSkeleton::ItemBool( currentGroup(), QString::fromLatin1( "Save Playlist" ), mSavePlaylist, true );
  addItem( itemSavePlaylist, QString::fromLatin1( "SavePlaylist" ) );
  KConfigSkeleton::ItemBool  *itemFollowSymlinks;
  itemFollowSymlinks = new KConfigSkeleton::ItemBool( currentGroup(), QString::fromLatin1( "Follow Symlinks" ), mFollowSymlinks, true );
  addItem( itemFollowSymlinks, QString::fromLatin1( "FollowSymlinks" ) );
  KConfigSkeleton::ItemBool  *itemTimeDisplayRemaining;
  itemTimeDisplayRemaining = new KConfigSkeleton::ItemBool( currentGroup(), QString::fromLatin1( "Time Display Remaining" ), mTimeDisplayRemaining, false );
  addItem( itemTimeDisplayRemaining, QString::fromLatin1( "TimeDisplayRemaining" ) );
  KConfigSkeleton::ItemBool  *itemUseScores;
  itemUseScores = new KConfigSkeleton::ItemBool( currentGroup(), QString::fromLatin1( "Use Scores" ), mUseScores, true );
  addItem( itemUseScores, QString::fromLatin1( "UseScores" ) );
  KConfigSkeleton::ItemBool  *itemUseRatings;
  itemUseRatings = new KConfigSkeleton::ItemBool( currentGroup(), QString::fromLatin1( "Use Ratings" ), mUseRatings, false );
  addItem( itemUseRatings, QString::fromLatin1( "UseRatings" ) );
  QValueList<KConfigSkeleton::ItemEnum::Choice> valuesRepeat;
  {
    KConfigSkeleton::ItemEnum::Choice choice;
    choice.name = QString::fromLatin1( "Off" );
    valuesRepeat.append( choice );
  }
  {
    KConfigSkeleton::ItemEnum::Choice choice;
    choice.name = QString::fromLatin1( "Track" );
    valuesRepeat.append( choice );
  }
  {
    KConfigSkeleton::ItemEnum::Choice choice;
    choice.name = QString::fromLatin1( "Album" );
    valuesRepeat.append( choice );
  }
  {
    KConfigSkeleton::ItemEnum::Choice choice;
    choice.name = QString::fromLatin1( "Playlist" );
    valuesRepeat.append( choice );
  }
  KConfigSkeleton::ItemEnum  *itemRepeat;
  itemRepeat = new KConfigSkeleton::ItemEnum( currentGroup(), QString::fromLatin1( "Repeat" ), mRepeat, valuesRepeat, EnumRepeat::Off );
  addItem( itemRepeat, QString::fromLatin1( "Repeat" ) );
  QValueList<KConfigSkeleton::ItemEnum::Choice> valuesFavorTracks;
  {
    KConfigSkeleton::ItemEnum::Choice choice;
    choice.name = QString::fromLatin1( "Off" );
    valuesFavorTracks.append( choice );
  }
  {
    KConfigSkeleton::ItemEnum::Choice choice;
    choice.name = QString::fromLatin1( "HigherScores" );
    valuesFavorTracks.append( choice );
  }
  {
    KConfigSkeleton::ItemEnum::Choice choice;
    choice.name = QString::fromLatin1( "HigherRatings" );
    valuesFavorTracks.append( choice );
  }
  {
    KConfigSkeleton::ItemEnum::Choice choice;
    choice.name = QString::fromLatin1( "LessRecentlyPlayed" );
    valuesFavorTracks.append( choice );
  }
  KConfigSkeleton::ItemEnum  *itemFavorTracks;
  itemFavorTracks = new KConfigSkeleton::ItemEnum( currentGroup(), QString::fromLatin1( "Favor Tracks" ), mFavorTracks, valuesFavorTracks, EnumFavorTracks::Off );
  addItem( itemFavorTracks, QString::fromLatin1( "FavorTracks" ) );
  QValueList<KConfigSkeleton::ItemEnum::Choice> valuesRandomMode;
  {
    KConfigSkeleton::ItemEnum::Choice choice;
    choice.name = QString::fromLatin1( "Off" );
    valuesRandomMode.append( choice );
  }
  {
    KConfigSkeleton::ItemEnum::Choice choice;
    choice.name = QString::fromLatin1( "Tracks" );
    valuesRandomMode.append( choice );
  }
  {
    KConfigSkeleton::ItemEnum::Choice choice;
    choice.name = QString::fromLatin1( "Albums" );
    valuesRandomMode.append( choice );
  }
  KConfigSkeleton::ItemEnum  *itemRandomMode;
  itemRandomMode = new KConfigSkeleton::ItemEnum( currentGroup(), QString::fromLatin1( "Random Mode" ), mRandomMode, valuesRandomMode, EnumRandomMode::Off );
  addItem( itemRandomMode, QString::fromLatin1( "RandomMode" ) );
  KConfigSkeleton::ItemString  *itemLastDynamicMode;
  itemLastDynamicMode = new KConfigSkeleton::ItemString( currentGroup(), QString::fromLatin1( "Last Dynamic Mode" ), mLastDynamicMode, QString::fromLatin1( "Random Mix" ) );
  addItem( itemLastDynamicMode, QString::fromLatin1( "LastDynamicMode" ) );
  KConfigSkeleton::ItemString  *itemLastScoreScript;
  itemLastScoreScript = new KConfigSkeleton::ItemString( currentGroup(), QString::fromLatin1( "Last Score Script" ), mLastScoreScript );
  addItem( itemLastScoreScript, QString::fromLatin1( "LastScoreScript" ) );
  KConfigSkeleton::ItemBool  *itemShowTrayIcon;
  itemShowTrayIcon = new KConfigSkeleton::ItemBool( currentGroup(), QString::fromLatin1( "Show Tray Icon" ), mShowTrayIcon, true );
  addItem( itemShowTrayIcon, QString::fromLatin1( "ShowTrayIcon" ) );
  KConfigSkeleton::ItemBool  *itemAnimateTrayIcon;
  itemAnimateTrayIcon = new KConfigSkeleton::ItemBool( currentGroup(), QString::fromLatin1( "Animate Tray Icon" ), mAnimateTrayIcon, false );
  addItem( itemAnimateTrayIcon, QString::fromLatin1( "AnimateTrayIcon" ) );
  KConfigSkeleton::ItemBool  *itemShowPlayerWindow;
  itemShowPlayerWindow = new KConfigSkeleton::ItemBool( currentGroup(), QString::fromLatin1( "Show Player Window" ), mShowPlayerWindow, false );
  addItem( itemShowPlayerWindow, QString::fromLatin1( "ShowPlayerWindow" ) );
  KConfigSkeleton::ItemBool  *itemShowMoodbar;
  itemShowMoodbar = new KConfigSkeleton::ItemBool( currentGroup(), QString::fromLatin1( "Show Moodbar" ), mShowMoodbar, false );
  addItem( itemShowMoodbar, QString::fromLatin1( "ShowMoodbar" ) );
  KConfigSkeleton::ItemBool  *itemCalculateMoodOnPlay;
  itemCalculateMoodOnPlay = new KConfigSkeleton::ItemBool( currentGroup(), QString::fromLatin1( "Calculate Mood On Play" ), mCalculateMoodOnPlay, true );
  addItem( itemCalculateMoodOnPlay, QString::fromLatin1( "CalculateMoodOnPlay" ) );
  KConfigSkeleton::ItemBool  *itemCalculateMoodOnQueue;
  itemCalculateMoodOnQueue = new KConfigSkeleton::ItemBool( currentGroup(), QString::fromLatin1( "Calculate Mood On Queue" ), mCalculateMoodOnQueue, true );
  addItem( itemCalculateMoodOnQueue, QString::fromLatin1( "CalculateMoodOnQueue" ) );
  KConfigSkeleton::ItemBool  *itemMoodsWithMusic;
  itemMoodsWithMusic = new KConfigSkeleton::ItemBool( currentGroup(), QString::fromLatin1( "Moods With Music" ), mMoodsWithMusic, false );
  addItem( itemMoodsWithMusic, QString::fromLatin1( "MoodsWithMusic" ) );
  KConfigSkeleton::ItemBool  *itemMakeMoodier;
  itemMakeMoodier = new KConfigSkeleton::ItemBool( currentGroup(), QString::fromLatin1( "Make Moodier" ), mMakeMoodier, true );
  addItem( itemMakeMoodier, QString::fromLatin1( "MakeMoodier" ) );
  KConfigSkeleton::ItemInt  *itemAlterMood;
  itemAlterMood = new KConfigSkeleton::ItemInt( currentGroup(), QString::fromLatin1( "AlterMood" ), mAlterMood, 0 );
  addItem( itemAlterMood, QString::fromLatin1( "AlterMood" ) );
  KConfigSkeleton::ItemInt  *itemMoodbarColumnSize;
  itemMoodbarColumnSize = new KConfigSkeleton::ItemInt( currentGroup(), QString::fromLatin1( "MoodbarColumnSize" ), mMoodbarColumnSize, 100 );
  addItem( itemMoodbarColumnSize, QString::fromLatin1( "MoodbarColumnSize" ) );
  KConfigSkeleton::ItemBool  *itemShowToolbar;
  itemShowToolbar = new KConfigSkeleton::ItemBool( currentGroup(), QString::fromLatin1( "Show Toolbar" ), mShowToolbar, true );
  addItem( itemShowToolbar, QString::fromLatin1( "ShowToolbar" ) );
  KConfigSkeleton::ItemInt  *itemCoverPreviewSize;
  itemCoverPreviewSize = new KConfigSkeleton::ItemInt( currentGroup(), QString::fromLatin1( "Cover Preview Size" ), mCoverPreviewSize, 100 );
  addItem( itemCoverPreviewSize, QString::fromLatin1( "CoverPreviewSize" ) );
  KConfigSkeleton::ItemBool  *itemDirectoriesRecursively;
  itemDirectoriesRecursively = new KConfigSkeleton::ItemBool( currentGroup(), QString::fromLatin1( "Directories Recursively" ), mDirectoriesRecursively, true );
  addItem( itemDirectoriesRecursively, QString::fromLatin1( "DirectoriesRecursively" ) );
  KConfigSkeleton::ItemInt  *itemTrackDelayLength;
  itemTrackDelayLength = new KConfigSkeleton::ItemInt( currentGroup(), QString::fromLatin1( "Track Delay Length" ), mTrackDelayLength, 0 );
  addItem( itemTrackDelayLength, QString::fromLatin1( "TrackDelayLength" ) );
  KConfigSkeleton::ItemBool  *itemPlaylistWindowEnabled;
  itemPlaylistWindowEnabled = new KConfigSkeleton::ItemBool( currentGroup(), QString::fromLatin1( "Playlist Window Enabled" ), mPlaylistWindowEnabled, true );
  addItem( itemPlaylistWindowEnabled, QString::fromLatin1( "PlaylistWindowEnabled" ) );
  KConfigSkeleton::ItemInt  *itemUndoLevels;
  itemUndoLevels = new KConfigSkeleton::ItemInt( currentGroup(), QString::fromLatin1( "Undo Levels" ), mUndoLevels, 30 );
  addItem( itemUndoLevels, QString::fromLatin1( "UndoLevels" ) );
  KConfigSkeleton::ItemInt  *itemCurrentAnalyzer;
  itemCurrentAnalyzer = new KConfigSkeleton::ItemInt( currentGroup(), QString::fromLatin1( "Current Analyzer" ), mCurrentAnalyzer, -1 );
  addItem( itemCurrentAnalyzer, QString::fromLatin1( "CurrentAnalyzer" ) );
  KConfigSkeleton::ItemInt  *itemCurrentPlaylistAnalyzer;
  itemCurrentPlaylistAnalyzer = new KConfigSkeleton::ItemInt( currentGroup(), QString::fromLatin1( "Current Playlist Analyzer" ), mCurrentPlaylistAnalyzer, 0 );
  addItem( itemCurrentPlaylistAnalyzer, QString::fromLatin1( "CurrentPlaylistAnalyzer" ) );
  QValueList<int> defaultPlaylistWindowSplitter;
  defaultPlaylistWindowSplitter.append( 70 );
  defaultPlaylistWindowSplitter.append( 140 );

  KConfigSkeleton::ItemIntList  *itemPlaylistWindowSplitter;
  itemPlaylistWindowSplitter = new KConfigSkeleton::ItemIntList( currentGroup(), QString::fromLatin1( "Playlist Window Splitter" ), mPlaylistWindowSplitter, defaultPlaylistWindowSplitter );
  addItem( itemPlaylistWindowSplitter, QString::fromLatin1( "PlaylistWindowSplitter" ) );
  KConfigSkeleton::ItemBool  *itemShowSplashscreen;
  itemShowSplashscreen = new KConfigSkeleton::ItemBool( currentGroup(), QString::fromLatin1( "Show Splashscreen" ), mShowSplashscreen, true );
  addItem( itemShowSplashscreen, QString::fromLatin1( "ShowSplashscreen" ) );
  KConfigSkeleton::ItemString  *itemContextBrowserStyleSheet;
  itemContextBrowserStyleSheet = new KConfigSkeleton::ItemString( currentGroup(), QString::fromLatin1( "ContextBrowser StyleSheet" ), mContextBrowserStyleSheet, QString::fromLatin1( "Default" ) );
  addItem( itemContextBrowserStyleSheet, QString::fromLatin1( "ContextBrowserStyleSheet" ) );
  KConfigSkeleton::ItemBool  *itemShowMenuBar;
  itemShowMenuBar = new KConfigSkeleton::ItemBool( currentGroup(), QString::fromLatin1( "Show Menu Bar" ), mShowMenuBar, true );
  addItem( itemShowMenuBar, QString::fromLatin1( "ShowMenuBar" ) );
  KConfigSkeleton::ItemBool  *itemRelativePlaylist;
  itemRelativePlaylist = new KConfigSkeleton::ItemBool( currentGroup(), QString::fromLatin1( "Relative Playlist" ), mRelativePlaylist, false );
  addItem( itemRelativePlaylist, QString::fromLatin1( "RelativePlaylist" ) );
  KConfigSkeleton::ItemBool  *itemOverwriteFiles;
  itemOverwriteFiles = new KConfigSkeleton::ItemBool( currentGroup(), QString::fromLatin1( "Overwrite Files" ), mOverwriteFiles, false );
  addItem( itemOverwriteFiles, QString::fromLatin1( "OverwriteFiles" ) );
  KConfigSkeleton::ItemBool  *itemGroupByFiletype;
  itemGroupByFiletype = new KConfigSkeleton::ItemBool( currentGroup(), QString::fromLatin1( "Group By Filetype" ), mGroupByFiletype, false );
  addItem( itemGroupByFiletype, QString::fromLatin1( "GroupByFiletype" ) );
  KConfigSkeleton::ItemBool  *itemGroupArtists;
  itemGroupArtists = new KConfigSkeleton::ItemBool( currentGroup(), QString::fromLatin1( "Group Artists" ), mGroupArtists, true );
  addItem( itemGroupArtists, QString::fromLatin1( "GroupArtists" ) );
  KConfigSkeleton::ItemBool  *itemIgnoreThe;
  itemIgnoreThe = new KConfigSkeleton::ItemBool( currentGroup(), QString::fromLatin1( "Ignore The" ), mIgnoreThe, true );
  addItem( itemIgnoreThe, QString::fromLatin1( "IgnoreThe" ) );
  KConfigSkeleton::ItemBool  *itemReplaceSpace;
  itemReplaceSpace = new KConfigSkeleton::ItemBool( currentGroup(), QString::fromLatin1( "Replace Space" ), mReplaceSpace, false );
  addItem( itemReplaceSpace, QString::fromLatin1( "ReplaceSpace" ) );
  KConfigSkeleton::ItemBool  *itemCoverIcons;
  itemCoverIcons = new KConfigSkeleton::ItemBool( currentGroup(), QString::fromLatin1( "Cover Icons" ), mCoverIcons, true );
  addItem( itemCoverIcons, QString::fromLatin1( "CoverIcons" ) );
  KConfigSkeleton::ItemInt  *itemOrganizeDirectory;
  itemOrganizeDirectory = new KConfigSkeleton::ItemInt( currentGroup(), QString::fromLatin1( "Organize Directory" ), mOrganizeDirectory, 0 );
  addItem( itemOrganizeDirectory, QString::fromLatin1( "OrganizeDirectory" ) );
  KConfigSkeleton::ItemBool  *itemVfatCompatible;
  itemVfatCompatible = new KConfigSkeleton::ItemBool( currentGroup(), QString::fromLatin1( "Vfat Compatible" ), mVfatCompatible, true );
  addItem( itemVfatCompatible, QString::fromLatin1( "VfatCompatible" ) );
  KConfigSkeleton::ItemBool  *itemAsciiOnly;
  itemAsciiOnly = new KConfigSkeleton::ItemBool( currentGroup(), QString::fromLatin1( "Ascii Only" ), mAsciiOnly, false );
  addItem( itemAsciiOnly, QString::fromLatin1( "AsciiOnly" ) );
  KConfigSkeleton::ItemBool  *itemUseCustomScheme;
  itemUseCustomScheme = new KConfigSkeleton::ItemBool( currentGroup(), QString::fromLatin1( "Use Custom Scheme" ), mUseCustomScheme, false );
  addItem( itemUseCustomScheme, QString::fromLatin1( "UseCustomScheme" ) );
  KConfigSkeleton::ItemString  *itemCustomScheme;
  itemCustomScheme = new KConfigSkeleton::ItemString( currentGroup(), QString::fromLatin1( "Custom Scheme" ), mCustomScheme, QString::fromLatin1( "%folder/%filetype/%theartist/%album/%track_-_%title.%filetype" ) );
  addItem( itemCustomScheme, QString::fromLatin1( "CustomScheme" ) );
  KConfigSkeleton::ItemString  *itemReplacementRegexp;
  itemReplacementRegexp = new KConfigSkeleton::ItemString( currentGroup(), QString::fromLatin1( "Replacement Regexp" ), mReplacementRegexp );
  addItem( itemReplacementRegexp, QString::fromLatin1( "ReplacementRegexp" ) );
  KConfigSkeleton::ItemString  *itemReplacementString;
  itemReplacementString = new KConfigSkeleton::ItemString( currentGroup(), QString::fromLatin1( "Replacement String" ), mReplacementString );
  addItem( itemReplacementString, QString::fromLatin1( "ReplacementString" ) );
  KConfigSkeleton::ItemString  *itemExternalBrowser;
  itemExternalBrowser = new KConfigSkeleton::ItemString( currentGroup(), QString::fromLatin1( "External Browser" ), mExternalBrowser, QString::fromLatin1( "kfmclient openURL" ) );
  addItem( itemExternalBrowser, QString::fromLatin1( "ExternalBrowser" ) );
  KConfigSkeleton::ItemBool  *itemUseCustomIconTheme;
  itemUseCustomIconTheme = new KConfigSkeleton::ItemBool( currentGroup(), QString::fromLatin1( "Use Custom Icon Theme" ), mUseCustomIconTheme, true );
  addItem( itemUseCustomIconTheme, QString::fromLatin1( "UseCustomIconTheme" ) );
  KConfigSkeleton::ItemInt  *itemCollectionBrowserViewMode;
  itemCollectionBrowserViewMode = new KConfigSkeleton::ItemInt( currentGroup(), QString::fromLatin1( "Collection Browser View Mode" ), mCollectionBrowserViewMode, 0 );
  addItem( itemCollectionBrowserViewMode, QString::fromLatin1( "CollectionBrowserViewMode" ) );

  setCurrentGroup( QString::fromLatin1( "Playback" ) );

  KConfigSkeleton::ItemInt  *itemMasterVolume;
  itemMasterVolume = new KConfigSkeleton::ItemInt( currentGroup(), QString::fromLatin1( "Master Volume" ), mMasterVolume, 80 );
  itemMasterVolume->setMinValue(0);
  itemMasterVolume->setMaxValue(100);
  addItem( itemMasterVolume, QString::fromLatin1( "MasterVolume" ) );
  KConfigSkeleton::ItemBool  *itemCrossfade;
  itemCrossfade = new KConfigSkeleton::ItemBool( currentGroup(), QString::fromLatin1( "Crossfade" ), mCrossfade, false );
  addItem( itemCrossfade, QString::fromLatin1( "Crossfade" ) );
  KConfigSkeleton::ItemInt  *itemCrossfadeLength;
  itemCrossfadeLength = new KConfigSkeleton::ItemInt( currentGroup(), QString::fromLatin1( "Crossfade Length" ), mCrossfadeLength, 3000 );
  itemCrossfadeLength->setMinValue(1500);
  addItem( itemCrossfadeLength, QString::fromLatin1( "CrossfadeLength" ) );
  KConfigSkeleton::ItemBool  *itemCrossfadeManualOnly;
  itemCrossfadeManualOnly = new KConfigSkeleton::ItemBool( currentGroup(), QString::fromLatin1( "Crossfade Manual Only" ), mCrossfadeManualOnly, false );
  addItem( itemCrossfadeManualOnly, QString::fromLatin1( "CrossfadeManualOnly" ) );
  KConfigSkeleton::ItemString  *itemSoundSystem;
  itemSoundSystem = new KConfigSkeleton::ItemString( currentGroup(), QString::fromLatin1( "Sound System" ), mSoundSystem );
  addItem( itemSoundSystem, QString::fromLatin1( "SoundSystem" ) );
  KConfigSkeleton::ItemBool  *itemEqualizerEnabled;
  itemEqualizerEnabled = new KConfigSkeleton::ItemBool( currentGroup(), QString::fromLatin1( "Equalizer Enabled" ), mEqualizerEnabled, false );
  addItem( itemEqualizerEnabled, QString::fromLatin1( "EqualizerEnabled" ) );
  KConfigSkeleton::ItemInt  *itemEqualizerPreamp;
  itemEqualizerPreamp = new KConfigSkeleton::ItemInt( currentGroup(), QString::fromLatin1( "Equalizer Preamp" ), mEqualizerPreamp, 0 );
  itemEqualizerPreamp->setMinValue(-100);
  itemEqualizerPreamp->setMaxValue(100);
  addItem( itemEqualizerPreamp, QString::fromLatin1( "EqualizerPreamp" ) );
  QValueList<int> defaultEqualizerGains;
  defaultEqualizerGains.append( 0 );
  defaultEqualizerGains.append(  0 );
  defaultEqualizerGains.append(  0 );
  defaultEqualizerGains.append(  0 );
  defaultEqualizerGains.append(  0 );
  defaultEqualizerGains.append(  0 );
  defaultEqualizerGains.append(  0 );
  defaultEqualizerGains.append(  0 );
  defaultEqualizerGains.append(  0 );
  defaultEqualizerGains.append(  0 );

  KConfigSkeleton::ItemIntList  *itemEqualizerGains;
  itemEqualizerGains = new KConfigSkeleton::ItemIntList( currentGroup(), QString::fromLatin1( "Equalizer Gains" ), mEqualizerGains, defaultEqualizerGains );
  addItem( itemEqualizerGains, QString::fromLatin1( "EqualizerGains" ) );
  KConfigSkeleton::ItemString  *itemEqualizerPreset;
  itemEqualizerPreset = new KConfigSkeleton::ItemString( currentGroup(), QString::fromLatin1( "Equalizer Preset" ), mEqualizerPreset, QString::fromLatin1( "Zero" ) );
  addItem( itemEqualizerPreset, QString::fromLatin1( "EqualizerPreset" ) );

  setCurrentGroup( QString::fromLatin1( "Cover Manager" ) );

  KConfigSkeleton::ItemString  *itemAmazonLocale;
  itemAmazonLocale = new KConfigSkeleton::ItemString( currentGroup(), QString::fromLatin1( "Amazon Locale" ), mAmazonLocale, QString::fromLatin1( "us" ) );
  addItem( itemAmazonLocale, QString::fromLatin1( "AmazonLocale" ) );

  setCurrentGroup( QString::fromLatin1( "Wikipedia" ) );

  KConfigSkeleton::ItemString  *itemWikipediaLocale;
  itemWikipediaLocale = new KConfigSkeleton::ItemString( currentGroup(), QString::fromLatin1( "Wikipedia Locale" ), mWikipediaLocale, QString::fromLatin1( "en" ) );
  addItem( itemWikipediaLocale, QString::fromLatin1( "WikipediaLocale" ) );

  setCurrentGroup( QString::fromLatin1( "OSD" ) );

  KConfigSkeleton::ItemBool  *itemOsdEnabled;
  itemOsdEnabled = new KConfigSkeleton::ItemBool( currentGroup(), QString::fromLatin1( "Osd Enabled" ), mOsdEnabled, true );
  addItem( itemOsdEnabled, QString::fromLatin1( "OsdEnabled" ) );
  KConfigSkeleton::ItemBool  *itemOsdUsePlaylistColumns;
  itemOsdUsePlaylistColumns = new KConfigSkeleton::ItemBool( currentGroup(), QString::fromLatin1( "Osd Use Playlist Columns" ), mOsdUsePlaylistColumns, true );
  addItem( itemOsdUsePlaylistColumns, QString::fromLatin1( "OsdUsePlaylistColumns" ) );
  KConfigSkeleton::ItemString  *itemOsdText;
  itemOsdText = new KConfigSkeleton::ItemString( currentGroup(), QString::fromLatin1( "Osd Text" ), mOsdText, QString::fromLatin1( "%artist - %title {(%length)}\\n%album" ) );
  addItem( itemOsdText, QString::fromLatin1( "OsdText" ) );
  KConfigSkeleton::ItemFont  *itemOsdFont;
  itemOsdFont = new KConfigSkeleton::ItemFont( currentGroup(), QString::fromLatin1( "Osd Font" ), mOsdFont, QFont("Arial",16) );
  addItem( itemOsdFont, QString::fromLatin1( "OsdFont" ) );
  KConfigSkeleton::ItemBool  *itemOsdDrawShadow;
  itemOsdDrawShadow = new KConfigSkeleton::ItemBool( currentGroup(), QString::fromLatin1( "Osd Draw Shadow" ), mOsdDrawShadow, true );
  addItem( itemOsdDrawShadow, QString::fromLatin1( "OsdDrawShadow" ) );
  KConfigSkeleton::ItemBool  *itemOsdUseFakeTranslucency;
  itemOsdUseFakeTranslucency = new KConfigSkeleton::ItemBool( currentGroup(), QString::fromLatin1( "Osd Use Fake Translucency" ), mOsdUseFakeTranslucency, true );
  addItem( itemOsdUseFakeTranslucency, QString::fromLatin1( "OsdUseFakeTranslucency" ) );
  KConfigSkeleton::ItemBool  *itemOsdUseCustomColors;
  itemOsdUseCustomColors = new KConfigSkeleton::ItemBool( currentGroup(), QString::fromLatin1( "Osd Use Custom Colors" ), mOsdUseCustomColors, false );
  addItem( itemOsdUseCustomColors, QString::fromLatin1( "OsdUseCustomColors" ) );
  KConfigSkeleton::ItemColor  *itemOsdTextColor;
  itemOsdTextColor = new KConfigSkeleton::ItemColor( currentGroup(), QString::fromLatin1( "Osd Text Color" ), mOsdTextColor, QColor( "#ffff00" ) );
  addItem( itemOsdTextColor, QString::fromLatin1( "OsdTextColor" ) );
  KConfigSkeleton::ItemColor  *itemOsdBackgroundColor;
  itemOsdBackgroundColor = new KConfigSkeleton::ItemColor( currentGroup(), QString::fromLatin1( "Osd Background Color" ), mOsdBackgroundColor, QColor( "#1500a0" ) );
  addItem( itemOsdBackgroundColor, QString::fromLatin1( "OsdBackgroundColor" ) );
  KConfigSkeleton::ItemInt  *itemOsdDuration;
  itemOsdDuration = new KConfigSkeleton::ItemInt( currentGroup(), QString::fromLatin1( "Osd Duration" ), mOsdDuration, 5000 );
  itemOsdDuration->setMinValue(0);
  addItem( itemOsdDuration, QString::fromLatin1( "OsdDuration" ) );
  KConfigSkeleton::ItemInt  *itemOsdYOffset;
  itemOsdYOffset = new KConfigSkeleton::ItemInt( currentGroup(), QString::fromLatin1( "Osd Y Offset" ), mOsdYOffset, 50 );
  itemOsdYOffset->setMinValue(0);
  itemOsdYOffset->setMaxValue(10000);
  addItem( itemOsdYOffset, QString::fromLatin1( "OsdYOffset" ) );
  KConfigSkeleton::ItemInt  *itemOsdScreen;
  itemOsdScreen = new KConfigSkeleton::ItemInt( currentGroup(), QString::fromLatin1( "Osd Screen" ), mOsdScreen, 0 );
  addItem( itemOsdScreen, QString::fromLatin1( "OsdScreen" ) );
  KConfigSkeleton::ItemBool  *itemOsdCover;
  itemOsdCover = new KConfigSkeleton::ItemBool( currentGroup(), QString::fromLatin1( "Osd Cover" ), mOsdCover, true );
  addItem( itemOsdCover, QString::fromLatin1( "OsdCover" ) );
  QValueList<KConfigSkeleton::ItemEnum::Choice> valuesOsdAlignment;
  {
    KConfigSkeleton::ItemEnum::Choice choice;
    choice.name = QString::fromLatin1( "Left" );
    valuesOsdAlignment.append( choice );
  }
  {
    KConfigSkeleton::ItemEnum::Choice choice;
    choice.name = QString::fromLatin1( "Middle" );
    valuesOsdAlignment.append( choice );
  }
  {
    KConfigSkeleton::ItemEnum::Choice choice;
    choice.name = QString::fromLatin1( "Center" );
    valuesOsdAlignment.append( choice );
  }
  {
    KConfigSkeleton::ItemEnum::Choice choice;
    choice.name = QString::fromLatin1( "Right" );
    valuesOsdAlignment.append( choice );
  }
  KConfigSkeleton::ItemEnum  *itemOsdAlignment;
  itemOsdAlignment = new KConfigSkeleton::ItemEnum( currentGroup(), QString::fromLatin1( "Osd Alignment" ), mOsdAlignment, valuesOsdAlignment, EnumOsdAlignment::Center );
  addItem( itemOsdAlignment, QString::fromLatin1( "OsdAlignment" ) );

  setCurrentGroup( QString::fromLatin1( "Fonts" ) );

  KConfigSkeleton::ItemBool  *itemUseCustomFonts;
  itemUseCustomFonts = new KConfigSkeleton::ItemBool( currentGroup(), QString::fromLatin1( "Use Custom Fonts" ), mUseCustomFonts, false );
  addItem( itemUseCustomFonts, QString::fromLatin1( "UseCustomFonts" ) );
  KConfigSkeleton::ItemFont  *itemPlaylistWindowFont;
  itemPlaylistWindowFont = new KConfigSkeleton::ItemFont( currentGroup(), QString::fromLatin1( "Playlist Window Font" ), mPlaylistWindowFont );
  addItem( itemPlaylistWindowFont, QString::fromLatin1( "PlaylistWindowFont" ) );
  KConfigSkeleton::ItemFont  *itemPlayerWidgetFont;
  itemPlayerWidgetFont = new KConfigSkeleton::ItemFont( currentGroup(), QString::fromLatin1( "Player Widget Font" ), mPlayerWidgetFont );
  addItem( itemPlayerWidgetFont, QString::fromLatin1( "PlayerWidgetFont" ) );
  KConfigSkeleton::ItemFont  *itemContextBrowserFont;
  itemContextBrowserFont = new KConfigSkeleton::ItemFont( currentGroup(), QString::fromLatin1( "Context Browser Font" ), mContextBrowserFont );
  addItem( itemContextBrowserFont, QString::fromLatin1( "ContextBrowserFont" ) );

  setCurrentGroup( QString::fromLatin1( "Colors" ) );

  KConfigSkeleton::ItemBool  *itemSchemeAmarok;
  itemSchemeAmarok = new KConfigSkeleton::ItemBool( currentGroup(), QString::fromLatin1( "Scheme Amarok" ), mSchemeAmarok, false );
  addItem( itemSchemeAmarok, QString::fromLatin1( "SchemeAmarok" ) );
  KConfigSkeleton::ItemBool  *itemSchemeKDE;
  itemSchemeKDE = new KConfigSkeleton::ItemBool( currentGroup(), QString::fromLatin1( "Scheme KDE" ), mSchemeKDE, true );
  addItem( itemSchemeKDE, QString::fromLatin1( "SchemeKDE" ) );
  KConfigSkeleton::ItemBool  *itemSchemeCustom;
  itemSchemeCustom = new KConfigSkeleton::ItemBool( currentGroup(), QString::fromLatin1( "Scheme Custom" ), mSchemeCustom, false );
  addItem( itemSchemeCustom, QString::fromLatin1( "SchemeCustom" ) );
  KConfigSkeleton::ItemColor  *itemPlaylistWindowFgColor;
  itemPlaylistWindowFgColor = new KConfigSkeleton::ItemColor( currentGroup(), QString::fromLatin1( "Playlist Window Fg Color" ), mPlaylistWindowFgColor, QColor( "#80a0ff" ) );
  addItem( itemPlaylistWindowFgColor, QString::fromLatin1( "PlaylistWindowFgColor" ) );
  KConfigSkeleton::ItemColor  *itemPlaylistWindowBgColor;
  itemPlaylistWindowBgColor = new KConfigSkeleton::ItemColor( currentGroup(), QString::fromLatin1( "Playlist Window Bg Color" ), mPlaylistWindowBgColor, QColor( "#000000" ) );
  addItem( itemPlaylistWindowBgColor, QString::fromLatin1( "PlaylistWindowBgColor" ) );

  setCurrentGroup( QString::fromLatin1( "Session" ) );

  KConfigSkeleton::ItemBool  *itemResumePlayback;
  itemResumePlayback = new KConfigSkeleton::ItemBool( currentGroup(), QString::fromLatin1( "Resume Playback" ), mResumePlayback, false );
  addItem( itemResumePlayback, QString::fromLatin1( "ResumePlayback" ) );
  KConfigSkeleton::ItemPath  *itemResumeTrack;
  itemResumeTrack = new KConfigSkeleton::ItemPath( currentGroup(), QString::fromLatin1( "Resume Track" ), mResumeTrack );
  addItem( itemResumeTrack, QString::fromLatin1( "ResumeTrack" ) );
  KConfigSkeleton::ItemInt  *itemResumeTime;
  itemResumeTime = new KConfigSkeleton::ItemInt( currentGroup(), QString::fromLatin1( "Resume Time" ), mResumeTime );
  addItem( itemResumeTime, QString::fromLatin1( "ResumeTime" ) );

  setCurrentGroup( QString::fromLatin1( "Collection" ) );

  KConfigSkeleton::ItemString  *itemDatabaseEngine;
  itemDatabaseEngine = new KConfigSkeleton::ItemString( currentGroup(), QString::fromLatin1( "DatabaseEngine" ), mDatabaseEngine, QString::fromLatin1( "SQLite" ) );
  addItem( itemDatabaseEngine, QString::fromLatin1( "DatabaseEngine" ) );
  KConfigSkeleton::ItemBool  *itemScanRecursively;
  itemScanRecursively = new KConfigSkeleton::ItemBool( currentGroup(), QString::fromLatin1( "Scan Recursively" ), mScanRecursively, true );
  addItem( itemScanRecursively, QString::fromLatin1( "ScanRecursively" ) );
  KConfigSkeleton::ItemBool  *itemMonitorChanges;
  itemMonitorChanges = new KConfigSkeleton::ItemBool( currentGroup(), QString::fromLatin1( "Monitor Changes" ), mMonitorChanges, true );
  addItem( itemMonitorChanges, QString::fromLatin1( "MonitorChanges" ) );
  KConfigSkeleton::ItemStringList  *itemCollectionFolders;
  itemCollectionFolders = new KConfigSkeleton::ItemStringList( currentGroup(), QString::fromLatin1( "Collection Folders" ), mCollectionFolders );
  addItem( itemCollectionFolders, QString::fromLatin1( "CollectionFolders" ) );
  KConfigSkeleton::ItemBool  *itemAdvancedTagFeatures;
  itemAdvancedTagFeatures = new KConfigSkeleton::ItemBool( currentGroup(), QString::fromLatin1( "AdvancedTagFeatures" ), mAdvancedTagFeatures, false );
  addItem( itemAdvancedTagFeatures, QString::fromLatin1( "AdvancedTagFeatures" ) );

  setCurrentGroup( QString::fromLatin1( "MySql" ) );

  KConfigSkeleton::ItemString  *itemMySqlHost;
  itemMySqlHost = new KConfigSkeleton::ItemString( currentGroup(), QString::fromLatin1( "MySqlHost" ), mMySqlHost, QString::fromLatin1( "localhost" ) );
  addItem( itemMySqlHost, QString::fromLatin1( "MySqlHost" ) );
  KConfigSkeleton::ItemInt  *itemMySqlPort;
  itemMySqlPort = new KConfigSkeleton::ItemInt( currentGroup(), QString::fromLatin1( "MySqlPort" ), mMySqlPort, 3306 );
  addItem( itemMySqlPort, QString::fromLatin1( "MySqlPort" ) );
  KConfigSkeleton::ItemString  *itemMySqlDbName;
  itemMySqlDbName = new KConfigSkeleton::ItemString( currentGroup(), QString::fromLatin1( "MySqlDbName" ), mMySqlDbName, QString::fromLatin1( "amarok" ) );
  addItem( itemMySqlDbName, QString::fromLatin1( "MySqlDbName" ) );
  KConfigSkeleton::ItemString  *itemMySqlUser;
  itemMySqlUser = new KConfigSkeleton::ItemString( currentGroup(), QString::fromLatin1( "MySqlUser" ), mMySqlUser );
  addItem( itemMySqlUser, QString::fromLatin1( "MySqlUser" ) );
  KConfigSkeleton::ItemPassword  *itemMySqlPassword;
  itemMySqlPassword = new KConfigSkeleton::ItemPassword( currentGroup(), QString::fromLatin1( "MySqlPassword" ), mMySqlPassword );
  addItem( itemMySqlPassword, QString::fromLatin1( "MySqlPassword" ) );
  KConfigSkeleton::ItemString  *itemMySqlPassword2;
  itemMySqlPassword2 = new KConfigSkeleton::ItemString( currentGroup(), QString::fromLatin1( "MySqlPassword2" ), mMySqlPassword2 );
  addItem( itemMySqlPassword2, QString::fromLatin1( "MySqlPassword2" ) );

  setCurrentGroup( QString::fromLatin1( "Postgresql" ) );

  KConfigSkeleton::ItemString  *itemPostgresqlHost;
  itemPostgresqlHost = new KConfigSkeleton::ItemString( currentGroup(), QString::fromLatin1( "PostgresqlHost" ), mPostgresqlHost, QString::fromLatin1( "localhost" ) );
  addItem( itemPostgresqlHost, QString::fromLatin1( "PostgresqlHost" ) );
  KConfigSkeleton::ItemInt  *itemPostgresqlPort;
  itemPostgresqlPort = new KConfigSkeleton::ItemInt( currentGroup(), QString::fromLatin1( "PostgresqlPort" ), mPostgresqlPort, 5432 );
  addItem( itemPostgresqlPort, QString::fromLatin1( "PostgresqlPort" ) );
  KConfigSkeleton::ItemString  *itemPostgresqlDbName;
  itemPostgresqlDbName = new KConfigSkeleton::ItemString( currentGroup(), QString::fromLatin1( "PostgresqlDbName" ), mPostgresqlDbName, QString::fromLatin1( "amarok" ) );
  addItem( itemPostgresqlDbName, QString::fromLatin1( "PostgresqlDbName" ) );
  KConfigSkeleton::ItemString  *itemPostgresqlUser;
  itemPostgresqlUser = new KConfigSkeleton::ItemString( currentGroup(), QString::fromLatin1( "PostgresqlUser" ), mPostgresqlUser, QString::fromLatin1( "amarok" ) );
  addItem( itemPostgresqlUser, QString::fromLatin1( "PostgresqlUser" ) );
  KConfigSkeleton::ItemPassword  *itemPostgresqlPassword;
  itemPostgresqlPassword = new KConfigSkeleton::ItemPassword( currentGroup(), QString::fromLatin1( "PostgresqlPassword" ), mPostgresqlPassword );
  addItem( itemPostgresqlPassword, QString::fromLatin1( "PostgresqlPassword" ) );
  KConfigSkeleton::ItemString  *itemPostgresqlPassword2;
  itemPostgresqlPassword2 = new KConfigSkeleton::ItemString( currentGroup(), QString::fromLatin1( "PostgresqlPassword2" ), mPostgresqlPassword2 );
  addItem( itemPostgresqlPassword2, QString::fromLatin1( "PostgresqlPassword2" ) );

  setCurrentGroup( QString::fromLatin1( "Scrobbler" ) );

  KConfigSkeleton::ItemBool  *itemSubmitPlayedSongs;
  itemSubmitPlayedSongs = new KConfigSkeleton::ItemBool( currentGroup(), QString::fromLatin1( "SubmitPlayedSongs" ), mSubmitPlayedSongs, false );
  addItem( itemSubmitPlayedSongs, QString::fromLatin1( "SubmitPlayedSongs" ) );
  KConfigSkeleton::ItemString  *itemScrobblerUsername;
  itemScrobblerUsername = new KConfigSkeleton::ItemString( currentGroup(), QString::fromLatin1( "ScrobblerUsername" ), mScrobblerUsername );
  addItem( itemScrobblerUsername, QString::fromLatin1( "ScrobblerUsername" ) );
  KConfigSkeleton::ItemString  *itemScrobblerPassword;
  itemScrobblerPassword = new KConfigSkeleton::ItemString( currentGroup(), QString::fromLatin1( "ScrobblerPassword" ), mScrobblerPassword );
  addItem( itemScrobblerPassword, QString::fromLatin1( "ScrobblerPassword" ) );
  KConfigSkeleton::ItemBool  *itemRetrieveSimilarArtists;
  itemRetrieveSimilarArtists = new KConfigSkeleton::ItemBool( currentGroup(), QString::fromLatin1( "RetrieveSimilarArtists" ), mRetrieveSimilarArtists, false );
  addItem( itemRetrieveSimilarArtists, QString::fromLatin1( "RetrieveSimilarArtists" ) );

  setCurrentGroup( QString::fromLatin1( "MediaDevice" ) );

  KConfigSkeleton::ItemString  *itemDeviceType;
  itemDeviceType = new KConfigSkeleton::ItemString( currentGroup(), QString::fromLatin1( "DeviceType" ), mDeviceType );
  addItem( itemDeviceType, QString::fromLatin1( "DeviceType" ) );
  KConfigSkeleton::ItemString  *itemMountPoint;
  itemMountPoint = new KConfigSkeleton::ItemString( currentGroup(), QString::fromLatin1( "MountPoint" ), mMountPoint );
  addItem( itemMountPoint, QString::fromLatin1( "MountPoint" ) );
  KConfigSkeleton::ItemString  *itemMountCommand;
  itemMountCommand = new KConfigSkeleton::ItemString( currentGroup(), QString::fromLatin1( "MountCommand" ), mMountCommand );
  addItem( itemMountCommand, QString::fromLatin1( "MountCommand" ) );
  KConfigSkeleton::ItemString  *itemUmountCommand;
  itemUmountCommand = new KConfigSkeleton::ItemString( currentGroup(), QString::fromLatin1( "UmountCommand" ), mUmountCommand );
  addItem( itemUmountCommand, QString::fromLatin1( "UmountCommand" ) );
  KConfigSkeleton::ItemBool  *itemAutoDeletePodcasts;
  itemAutoDeletePodcasts = new KConfigSkeleton::ItemBool( currentGroup(), QString::fromLatin1( "AutoDeletePodcasts" ), mAutoDeletePodcasts );
  addItem( itemAutoDeletePodcasts, QString::fromLatin1( "AutoDeletePodcasts" ) );
  KConfigSkeleton::ItemBool  *itemSyncStats;
  itemSyncStats = new KConfigSkeleton::ItemBool( currentGroup(), QString::fromLatin1( "SyncStats" ), mSyncStats );
  addItem( itemSyncStats, QString::fromLatin1( "SyncStats" ) );
}

AmarokConfig::~AmarokConfig()
{
  if ( mSelf == this )
    staticAmarokConfigDeleter.setObject( mSelf, 0, false );
}

