/* config.h.  Generated by configure.  */
/* config.h.in.  Generated from configure.in by autoheader.  */

/* Amazon cover download support enabled */
#define AMAZON_SUPPORT 1

/* Define to 1 if you have the <Carbon/Carbon.h> header file. */
/* #undef HAVE_CARBON_CARBON_H */

/* Define if you have the CoreAudio API */
/* #undef HAVE_COREAUDIO */

/* Define to 1 if you have the <crt_externs.h> header file. */
/* #undef HAVE_CRT_EXTERNS_H */

/* Defines if your system has the crypt function */
#define HAVE_CRYPT 1

/* Define to 1 if you have the <dlfcn.h> header file. */
#define HAVE_DLFCN_H 1

/* have HELIX */
/* #undef HAVE_HELIX */

/* have ifp */
/* #undef HAVE_IFP */

/* Define to 1 if you have the <ifp.h> header file. */
/* #undef HAVE_IFP_H */

/* have inotify */
#define HAVE_INOTIFY 1

/* Define to 1 if you have the <inttypes.h> header file. */
#define HAVE_INTTYPES_H 1

/* Define to 1 if you have the `itdb_get_mountpoint' function. */
/* #undef HAVE_ITDB_GET_MOUNTPOINT */

/* have libgpod movie flag */
/* #undef HAVE_ITDB_MOVIE_FLAG */

/* Define to 1 if you have the `itdb_track_set_thumbnails' function. */
/* #undef HAVE_ITDB_TRACK_SET_THUMBNAILS */

/* have libgpod */
/* #undef HAVE_LIBGPOD */

/* Define if you have libjpeg */
#define HAVE_LIBJPEG 1

/* have libnjb */
/* #undef HAVE_LIBNJB */

/* Define if you have libpng */
#define HAVE_LIBPNG 1

/* Define if you have a working libpthread (will enable threaded code) */
#define HAVE_LIBPTHREAD 1

/* have LIBVISUAL */
/* #undef HAVE_LIBVISUAL */

/* Define if you have libz */
#define HAVE_LIBZ 1

/* Define to 1 if you have the <linux/inotify.h> header file. */
#define HAVE_LINUX_INOTIFY_H 1

/* Define to 1 if you have the <memory.h> header file. */
#define HAVE_MEMORY_H 1

/* have mp4v2 */
/* #undef HAVE_MP4V2 */

/* Define to 1 if you have the <mp4.h> header file. */
/* #undef HAVE_MP4_H */

/* have NMM */
/* #undef HAVE_NMM */

/* Define if your system needs _NSGetEnviron to set up the environment */
/* #undef HAVE_NSGETENVIRON */

/* have Qt with OpenGL support */
#define HAVE_QGLWIDGET 1

/* Define if you have res_init */
#define HAVE_RES_INIT 1

/* Define if you have the res_init prototype */
#define HAVE_RES_INIT_PROTO 1

/* Define if you have a STL implementation by SGI */
#define HAVE_SGI_STL 1

/* Define to 1 if you have the `snprintf' function. */
#define HAVE_SNPRINTF 1

/* Define to 1 if you have the `statvfs' function. */
#define HAVE_STATVFS 1

/* Define to 1 if you have the <stdint.h> header file. */
#define HAVE_STDINT_H 1

/* Define to 1 if you have the <stdlib.h> header file. */
#define HAVE_STDLIB_H 1

/* Define to 1 if you have the <strings.h> header file. */
#define HAVE_STRINGS_H 1

/* Define to 1 if you have the <string.h> header file. */
#define HAVE_STRING_H 1

/* Define if you have strlcat */
/* #undef HAVE_STRLCAT */

/* Define if you have the strlcat prototype */
/* #undef HAVE_STRLCAT_PROTO */

/* Define if you have strlcpy */
/* #undef HAVE_STRLCPY */

/* Define if you have the strlcpy prototype */
/* #undef HAVE_STRLCPY_PROTO */

/* Define to 1 if you have the <systems.h> header file. */
/* #undef HAVE_SYSTEMS_H */

/* Define to 1 if you have the <sys/bitypes.h> header file. */
#define HAVE_SYS_BITYPES_H 1

/* Define to 1 if you have the <sys/stat.h> header file. */
#define HAVE_SYS_STAT_H 1

/* Define to 1 if you have the <sys/types.h> header file. */
#define HAVE_SYS_TYPES_H 1

/* have TagLib */
#define HAVE_TAGLIB 1

/* have TunePimp */
#define HAVE_TUNEPIMP 0

/* Define to 1 if you have the <unistd.h> header file. */
#define HAVE_UNISTD_H 1

/* Define to 1 if you have the <usb.h> header file. */
#define HAVE_USB_H 1

/* Define to 1 if you have the `vsnprintf' function. */
#define HAVE_VSNPRINTF 1

/* have Xine */
#define HAVE_XINE 1

/* have XMMS */
/* #undef HAVE_XMMS */

/* location of helix libs */
/* #undef HELIX_LIBS */

/* Suffix for lib directories */
#define KDELIBSUFF ""

/* Name of package */
#define PACKAGE "multimedia"

/* Define to the address where bug reports for this package should be sent. */
#define PACKAGE_BUGREPORT ""

/* Define to the full name of this package. */
#define PACKAGE_NAME ""

/* Define to the full name and version of this package. */
#define PACKAGE_STRING ""

/* Define to the one symbol short name of this package. */
#define PACKAGE_TARNAME ""

/* Define to the version of this package. */
#define PACKAGE_VERSION ""

/* sched_setaffinity takes three params */
#define SCHEDAFFINITY_3PARAMS 1

/* sched_setaffinity works correctly */
#define SCHEDAFFINITY_SUPPORT 1

/* The size of a `char *', as computed by sizeof. */
#define SIZEOF_CHAR_P 4

/* The size of a `int', as computed by sizeof. */
#define SIZEOF_INT 4

/* The size of a `long', as computed by sizeof. */
#define SIZEOF_LONG 4

/* The size of a `short', as computed by sizeof. */
#define SIZEOF_SHORT 2

/* The size of a `size_t', as computed by sizeof. */
#define SIZEOF_SIZE_T 4

/* The size of a `unsigned long', as computed by sizeof. */
#define SIZEOF_UNSIGNED_LONG 4

/* Determine pointer size for SQLite */
#define SQLITE_PTR_SZ SIZEOF_CHAR_P

/* Define to 1 if you have the ANSI C header files. */
#define STDC_HEADERS 1

/* If we use arts volume */
#define USE_ARTS 1

/* support ALSA in the helix-engine */
/* #undef USE_HELIX_ALSA */

/* MySql database support enabled */
/* #undef USE_MYSQL */

/* Postgresql database support enabled */
/* #undef USE_POSTGRESQL */

/* Version number of package */
#define VERSION "3.5.3"

/* Defined if compiling without arts */
/* #undef WITHOUT_ARTS */

/* Define the path to XMMS plugins */
#define XMMS_PLUGIN_PATH ""

/*
 * jpeg.h needs HAVE_BOOLEAN, when the system uses boolean in system
 * headers and I'm too lazy to write a configure test as long as only
 * unixware is related
 */
#ifdef _UNIXWARE
#define HAVE_BOOLEAN
#endif



/*
 * AIX defines FD_SET in terms of bzero, but fails to include <strings.h>
 * that defines bzero.
 */

#if defined(_AIX)
#include <strings.h>
#endif



#if defined(HAVE_NSGETENVIRON) && defined(HAVE_CRT_EXTERNS_H)
# include <sys/time.h>
# include <crt_externs.h>
# define environ (*_NSGetEnviron())
#endif



#if !defined(HAVE_RES_INIT_PROTO)
#ifdef __cplusplus
extern "C" {
#endif
int res_init(void);
#ifdef __cplusplus
}
#endif
#endif



#if !defined(HAVE_STRLCAT_PROTO)
#ifdef __cplusplus
extern "C" {
#endif
unsigned long strlcat(char*, const char*, unsigned long);
#ifdef __cplusplus
}
#endif
#endif



#if !defined(HAVE_STRLCPY_PROTO)
#ifdef __cplusplus
extern "C" {
#endif
unsigned long strlcpy(char*, const char*, unsigned long);
#ifdef __cplusplus
}
#endif
#endif



/*
 * On HP-UX, the declaration of vsnprintf() is needed every time !
 */

#if !defined(HAVE_VSNPRINTF) || defined(hpux)
#if __STDC__
#include <stdarg.h>
#include <stdlib.h>
#else
#include <varargs.h>
#endif
#ifdef __cplusplus
extern "C"
#endif
int vsnprintf(char *str, size_t n, char const *fmt, va_list ap);
#ifdef __cplusplus
extern "C"
#endif
int snprintf(char *str, size_t n, char const *fmt, ...);
#endif



#if defined(__SVR4) && !defined(__svr4__)
#define __svr4__ 1
#endif


/* type to use in place of socklen_t if not defined */
#define kde_socklen_t socklen_t

/* type to use in place of socklen_t if not defined (deprecated, use
   kde_socklen_t) */
#define ksize_t socklen_t
